
import { GoogleGenAI } from "@google/genai";
import { VideoResult } from "../types";

// Initialize Gemini Client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

interface AnimationRequest {
  topic: string;
  summary: string;
  style?: string;
}

export const generateGeminiAnimation = async (
  request: AnimationRequest, 
  cloudAssistEnabled: boolean,
  confirmCallback: () => Promise<boolean>
): Promise<VideoResult | null> => {
  
  if (!cloudAssistEnabled) {
    throw new Error("Cloud Assist is disabled.");
  }

  const confirmed = await confirmCallback();
  if (!confirmed) return null;

  try {
    // Using Veo model for video generation
    // Note: Video generation takes time. We simulate polling here or assume simple output.
    const operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: `Create a ${request.style || 'cinematic'} educational animation explaining: ${request.topic}. Key details: ${request.summary.substring(0, 100)}`,
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: '16:9'
      }
    });

    // Polling simulation (in a real app, use a proper poller)
    let op = operation;
    let attempts = 0;
    while (!op.done && attempts < 20) { // Max 30 seconds wait for demo
        await new Promise(resolve => setTimeout(resolve, 1500));
        op = await ai.operations.getVideosOperation({ operation: op });
        attempts++;
    }

    const videoUri = op.response?.generatedVideos?.[0]?.video?.uri;
    
    if (videoUri) {
        // In a real browser context, we need to fetch the blob via a proxy or append key if allowed.
        // For this demo, we return the URI directly, but note it might require auth headers in a real deployment.
        // We will mock a result if the API call was just a simulation for this codebase context.
        return {
            id: `gemini-${Date.now()}`,
            title: `AI Explainer: ${request.topic}`,
            description: `Generated by Gemini Veo. Style: ${request.style}`,
            thumbnail: 'https://via.placeholder.com/320x180?text=AI+Generated+Video', // Placeholder as we don't have a thumbnail gen
            url: `${videoUri}&key=${process.env.API_KEY}`,
            source: 'gemini',
            duration: '00:06', // Veo previews are short
            relevance: 1
        };
    }
    
    throw new Error("Video generation incomplete");

  } catch (error) {
    console.error("Gemini Animation Error:", error);
    // Fallback: Return a storyboard concept (mocked)
    return {
        id: `gemini-sb-${Date.now()}`,
        title: `Storyboard: ${request.topic}`,
        description: 'Video generation failed. Generated storyboard concept instead.',
        thumbnail: 'https://via.placeholder.com/320x180?text=Storyboard+Concept',
        url: '#',
        source: 'gemini',
        duration: 'Storyboard',
        relevance: 0.8
    };
  }
};
